Consider the below code to answer further questions:
import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)
Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

list_ = [ '1' , '2', '3'.'4','5']
array_list = np.array(object = list_)
list_ is a standard Python list, and its type is list. It can hold elements of any data type (e.g., strings, integers, etc.).

array_list is a NumPy array, and its type is numpy.ndarray. The elements in the NumPy array will be of a single type (in this case, strings since you initialized it with strings).

In [7]:
# Q2. Write a code to print the data type of each and every element of both the variables list_ and
# arra_list.

list_ = [ '1' , '2', '3','4','5']

for i in list_:
    print(type(i))

array_list = np.array(object = list_)
for i in array_list:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [10]:
# Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
# Will there be any difference in the data type of the elements present in both the variables, list_ and
# arra_list? If so then print the data types of each and every element present in both the variables, list_
# and arra_list.

# it will not change the data type of the elements present in list_ as it is still a list of strings.
# However, the data type of the elements in array_list will change to int as we have specified the dtype as int while creating the numpy array.
for i in list_:
    print(type(i))
for i in array_list:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [12]:
#Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

# Q4. Write a code to find the following characteristics of variable, num_array:
# (i) shape
# (ii) size

print(num_array.shape)
print(num_array.size)

(2, 3)
6


In [15]:
# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
# creation function.
import numpy as np
zero_array = np.zeros((3,3))

print(zero_array)

zero_array.shape

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


(3, 3)

In [16]:
#Q6. Create an identity matrix of shape (5,5) using numpy functions?
identity_matrix = np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
